### ISSUE TITLE
Connections to private IPs on port 7946 tcp/udp

### ISSUE THREAD

**Issue by Fermiron** [gladiusio/gladius-controld#76]
I see a lot of connections(~2'000/hour) to private range IPs from the controld service going to port 7946. 

- Mostly TCP(~90%) some UDP(~10%) Connections as well.
- Outgoing IPv4 connections only to private IPs, no incomming
- IPv6(about half the traffic) to and from public IPs

Could this possibly be a bug? Is it possible that the controld tries the private IP of the other nodes instead of the public IP?
I attached some tcpdumps. If you need some more info to debug the issue, feel free to ask.
[tcpdumps.zip](https://github.com/gladiusio/gladius-controld/files/2346352/tcpdumps.zip)

Setup Information:
- Ubuntu Linux 16.05
- Gladius 0.6.1
- Local IPs: 192.168.113.50 and fd2a:201:6820:5109::1:0
- networkd seems to work correctly, I received content and see outgoing traffic on port 8080(~25Mbit/s)

**Comment by broken-trigger** [comment]
tested via
tcpdump -nni wan-interface -e port 7946
and can confirm that, only ipv4 here

some debian distro
gladius 0.6.0

**Comment by broken-trigger** [comment]
windows 7 64bit
same problem
wan-ip > private ip of node operators
so sending ipv4 packages to nowhere

**Comment by code-merc** [comment]
Yeah this is something we've noticed with memberlist at scale and on certain distributions, not sure I can fix it easily as this isn't entirely it's intended use case. 

I'm actually in the process of swapping to a different p2p backend called [Noise](https://github.com/perlin-network/noise) that should help with some of the issues. Got much more control over sending and receiving messages.

**Comment by Fermiron** [comment]
This "Noise" sounds promissing. It will hopefully solve the issue.

It's interssting that my node seams to work anyway. Is the port 7946 traffic not vital for the system to work, or are maybe the handful ipv6 peers sufficent?

**Comment by code-merc** [comment]
So downloading the files actually works in conjunction with the p2p network. Essentially we have a network state that looks kinda like this:
```json
{
 "pool_data": {
    "required_content": ["blog.gladius.io/file_hash"]
 },
 "node_data_map": {
   "0xaddress": {
     "ip_address": "1.1.1.1",
     "disk_content" : ["blog.gladius.io/file_hash"]
    }
 }
}
```
Only accepted nodes can update their state, and once a node does any other node with the state can download the content from any node and verify the hash. So as long as you get the state at least once you should be able to get the files.

**Comment by code-merc** [comment]
You can actually take a look for yourself by running 
```
curl --request GET --url http://localhost:3001/api/p2p/state
```  
and looking for the required content. You can then call
```
curl --request POST \
  --url http://localhost:3001/api/p2p/state/content_links \
  --header 'content-type: application/json' \
  --data '{
	"content": ["blog.gladius.io/5573edfbcfb09f07956702f07f21ea2b24ba1dc98f3f09e21815d8219d1ebd87"]
}'
```
where you replace the content with what you want to find.

**Comment by Fermiron** [comment]
So basically I can check with your second API Call, which nodes are serving the specific content, is that correct?

`
{"message":"Got needed content links","success":true,"error":"","response":{"blog.gladius.io/df629121656857f3ee1e6c88d73b13a5b5a8a0ade6505dfd1f4a18c08738f4b9":
["http://85.195.234.187:8080/content?asset=df629121656857f3ee1e6c88d73b13a5b5a8a0ade6505dfd1f4a18c08738f4b9&website=blog.gladius.io",
"http://85.214.198.168:8080/content?asset=df629121656857f3ee1e6c88d73b13a5b5a8a0ade6505dfd1f4a18c08738f4b9&website=blog.gladius.io",
"http://165.227.16.209:8080/content?asset=df629121656857f3ee1e6c88d73b13a5b5a8a0ade6505dfd1f4a18c08738f4b9&website=blog.gladius.io"]},"txHash":null,"endpoint":"/api/p2p/state/content_links"}
`

So if I see two other links besides my own, this means the content is availbable on 3 nodes?

By the way, the links I get from this API call contain the public ipv4 address of the other nodes :)

**Comment by code-merc** [comment]
Yep, the first release we put out had issues syncing files the network. The code in feature/p2p-overhaul fixes most of those problems. 

And eventually those public ipv4 addresses will be something along the lines of `edge1.examplepool.com`
